Many changes since last commit. extract_proteins.py is now modularized into externally-callable functions. pmn-pipeline.py has WIP support for running revise_pf. pmn.py's invert_dictlist now supports scalar values in input dict. New functions counter_from_id, check_exists, socket_msg, send_ptools_cmd, ptools_so. refine_prepare.py now checks for supported python version. revise_pf.py now supports -gr argument to gelete portions of the gene name and is now callable as a function externally. Many new lisp functions. Fixes to the install_module script

diff --git a/perl_modules/install-module b/perl_modules/install-module
--- a/perl_modules/install-module
+++ b/perl_modules/install-module
@@ -18,23 +18,47 @@ else
 fi
 
 cd $mod_dir
-if ! perl Makefile.PL PREFIX=$PMN_PERL_MODS; then
-	echo "$mod_dir failed to configure"
-	exit 1
-fi
+if [[ -a Build.PL ]]; then
+	if ! perl Build.PL --prefix $PMN_PERL_MODS; then
+		echo "$mod_dir failed configure via Build.PL"
+		exit 1
+	fi
+	if [[ ! -a Build ]]; then
+		echo "$mod_dir Build.PL did not make a Build script. I don't know how to install this perl module"
+		exit 1
+	fi
+	if ! ./Build; then
+		echo "$mod_dir Build script failed"
+		exit 1
+	fi
+	if ! ./Build test; then
+		echo "$mod_dir failed post-build test(s)"
+		exit 1
+	fi
+	if ! ./Build install; then
+		echo "$mod_dir failed installation"
+		exit 1
+	fi
+	echo "$mod_dir installed successfully"
+elif [[ -a Makefile.PL ]]; then
+	if ! perl Makefile.PL PREFIX=$PMN_PERL_MODS; then
+		echo "$mod_dir failed configure via Makefile.PL"
+		exit 1
+	fi
 
-if ! make; then
-	echo "$mod_dir failed to build"
-	exit 1
-fi
+	if ! make; then
+		echo "$mod_dir failed to build"
+		exit 1
+	fi
 
-if ! make test; then
-	echo "$mod_dir failed post-build tests"
-	exit 1
-fi
+	if ! make test; then
+		echo "$mod_dir failed post-build tests"
+		exit 1
+	fi
 
-if ! make install; then
-	echo "$mod_dir failed install"
-	exit 1
+	if ! make install; then
+		echo "$mod_dir failed install"
+		exit 1
+	fi
+	echo "$mod_dir installed successfully"
 fi
-echo "$mod_dir installed successfully"
